[package]
name = "slack-greeter"
version = "0.1.0"
authors = ["Danny Lin <danny@kdrag0n.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack = "0.22.0"
toml = "0.5.5"
stderrlog = "0.4.3"
log = "0.4.8"
